### PR TITLE
Add `snailtracer` benchmark

### PR DESCRIPTION
**Pull request by ziyadedher**
**Note: this PR includes #1 cuz it made it easier**

Did some benchmarking using [snailtracer](https://github.com/karalabe/snailtracer) -- results are pretty good IMO:

~50ms using revm, ~113ms using pyrevm, eh not bad. I expected it to be a bit closer, but I imagine a good portion of this is Python FFI overhead. Haven't dug into it too much.

This isn't a perfect apples-to-apples comparison, the revm benchmark modifies the transaction context before starting the benchmark, this benchmark constructions the environment during the benchmark. With a little more effort we could probably remove any additional overhead due to that, but I don't think it's that big of a deal.

----

Baseline results using the `snailtracer` benchmark from [revm](https://github.com/bluealloy/revm):

```
Hello, world!
elapsed: 49.963531ms
0: 63.562866ms
1: 61.138572ms
2: 55.771676ms
3: 49.228193ms
4: 49.100465ms
5: 48.995046ms
6: 48.847959ms
7: 48.743462ms
8: 48.731132ms
9: 48.718941ms
10: 48.71229ms
11: 48.696701ms
12: 48.694723ms
13: 48.671922ms
14: 48.65721ms
15: 48.611618ms
16: 48.610157ms
17: 48.547279ms
18: 48.50588ms
19: 48.456446ms
20: 48.451354ms
21: 48.449931ms
22: 48.373144ms
23: 48.316536ms
24: 48.315507ms
end!
```

Results from this benchmark:

```
         21 function calls in 1.135 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.000    0.000    1.135    0.113 /home/ziyadedher/code/eth/pyrevm/bench/snailtracer/snailtracer.py:39(bench)
       10    1.135    0.113    1.135    0.113 {method 'call_raw' of 'builtins.EVM' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

### CODE REVIEW

**Review by gakonst — APPROVED** [review]
sweet! do we know how fast pyevm is?

**Comment by ziyadedher** [comment]
Huh... I completely forgot about the existence of pyevm lol. Lemme see if I can get this benchmark running there.

**Comment by ziyadedher** [comment]
Let's just say... slower. Average of ~39028ms per run. That's about 345x slower, wow. I tried to get the benchmark as barebones as possible, I think I actually trimmed it more than the benchmark for pyrevm, if you can spot anything that would be causing such a huge slowdown, let me know: https://gist.github.com/ziyadedher/d07610ad172cf25fff7d0558c522304d

**Comment by gakonst** [comment]
Suspect there's a lot of overhead due to pyevm doing header validation, vs just being a thin interpreter

**Comment by ziyadedher** [comment]
I did some pruning and (1) verified no header validation is being done and (2) no state is being committed in the critical paths for the pyevm benchmarks. Traced the code line-by-line and AFAICT it's just straight up transaction execution, running opcodes. I even got rid of the profiler in case that had some overhead.

I end up with ~15693ms per run of this benchmark compared to ~115ms for pyrevm under the same harness. That's 138x faster. Incredible. I don't see any reason to doubt this right now, but happy to be proved wrong.

**Comment by gakonst** [comment]
Wow that's wild, thank you for running this. Any way to reproduce the result with your pruned pyevm?

**Comment by ziyadedher** [comment]
Removed the profiler from the `pyevm` benchmark and updated the gist here: https://gist.github.com/ziyadedher/d07610ad172cf25fff7d0558c522304d

I just mocked out the StateAPI, basically commenting out all the DB functionality in [`eth/vm/state.py`](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/state.py#L58). I don't think this did much actually, disabling profiling seems to have had the largest effect. There actually isn't much going on in the critical path (other than layers and layers of abstractions).

In the gist, here's how the control flow goes. There's a lot of weird overriding and inheritance going on that makes it hard to manually trace:
- [`build_computation` call](https://gist.github.com/ziyadedher/d07610ad172cf25fff7d0558c522304d#file-snailtracer-pyevm-py-L83) is the entry point being benchmarked
- since I'm using Berlin the transaction executor is [`BerlinTransactionExecutor`](https://github.com/ethereum/py-evm/blob/master/eth/vm/forks/berlin/state.py)
- that handles [warming and whatnot](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/berlin/state.py#L25-L33), does some account DB stuff
- [calls into `FrontierTransactionExecutor.build_computation`](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/berlin/state.py#L35)
- that [gets transaction context](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/frontier/state.py#L115) (cheap, just creating a struct) and then [begins actual computation](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/frontier/state.py#L134) by calling into `BerlinComputation.apply_message` which inherits logic from [`FrontierComputation.apply_message`](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/spurious_dragon/computation.py#L46) but using Berlin [opcodes and precompiles](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/berlin/computation.py#L88-L89)
- after doing some cheap (mocked) account DB stuff, this [calls](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/forks/frontier/computation.py#L83-L87) into [`BaseComputation.apply_computation`](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/computation.py#L519)
- this [creates a context manager with a stack, memory, and some other stuff](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/computation.py#L523) (this is a little expensive)
- then in that context [starts calling opcodes](https://github.com/ethereum/py-evm/blob/c2a6ba2720f9972959bace961800bfd8b5b58295/eth/vm/computation.py#L551) (this is where the vast majority of time is spent)
- opcodes do all sorts of stuff, but the most expensive stuff being done according to the profile is:
    1. memory management (`mload`, `mstore` and extending the Python memory data structures), the Python data structures for storage and memory are extended ad-hoc and exactly to the amount needed (not amortized, though Python is probably doing some amortization here?)
    2. gas consumption, calling `consume_gas` 41 million times takes a little bit, there are a bunch of branches in that critical path
    3. all the other opcode-specific stuff

If someone wants to repro, I'd encourage mocking out the StateAPI to start, but also challenging some of the assumptions I made here about what's expensive and what's not. But the profiler output seems to corroborate those assumptions. 

----

Here's some profiler output. Note the walltimes are not true-to-life since the profiler adds significant overhead, but it gives a sense.

```
         576141973 function calls (566809707 primitive calls) in 203.218 seconds

   Ordered by: internal time
   List reduced from 299 to 25 due to restriction <25>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
 40571945   22.187    0.000  163.158    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/opcode.py:45(wrapped_logic_fn)
        5   19.798    3.960  203.217   40.643 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/computation.py:518(apply_computation)
 42172966   13.622    0.000   13.622    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/gas_meter.py:55(consume_gas)
  8607700   11.114    0.000   16.160    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/stack.py:135(pop_ints)
 41098906   10.584    0.000   23.842    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/computation.py:251(consume_gas)
 41070870    9.378    0.000    9.378    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/code_stream.py:47(__iter__)
  3247640    7.866    0.000   25.434    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/computation.py:202(extend_memory)
73628592/64414867    6.655    0.000    8.257    0.000 {built-in method builtins.len}
  1644380    6.501    0.000   11.223    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/memory.py:47(write)
  7283285    5.187    0.000   14.431    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/logic/stack.py:10(push_XX)
  8886545    4.635    0.000    8.180    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/stack.py:65(push_bytes)
 10408480    4.573    0.000    5.943    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/stack.py:203(dup)
  6495280    4.405    0.000    5.132    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/computation.py:85(memory_gas_cost)
  7760025    4.002    0.000    6.199    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/stack.py:57(push_int)
 10302555    3.749    0.000    5.512    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/validation.py:160(validate_uint256)
 12851413    3.152    0.000    4.485    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth_utils/encoding.py:5(big_endian_to_int)
 10408480    3.033    0.000    8.976    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/computation.py:287(stack_dup)
 44270476    2.892    0.000    2.892    0.000 {method 'append' of 'list' objects}
 10408480    2.746    0.000   11.722    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/logic/duplication.py:6(dup_XX)
  3431640    2.737    0.000   12.665    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/logic/arithmetic.py:16(add)
  3247640    2.671    0.000    5.694    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/memory.py:24(extend)
  5905345    2.584    0.000    4.102    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/stack.py:90(pop1_int)
  1644380    2.507    0.000   32.195    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/logic/memory.py:4(mstore)
  1291570    2.374    0.000    5.899    0.000 /home/ziyadedher/code/eth/pyrevm/.venv/lib/python3.10/site-packages/eth/vm/logic/arithmetic.py:123(sdiv)
 26973660    2.330    0.000    2.547    0.000 {built-in method builtins.isinstance}
 ```

**Comment by gakonst** [comment]
This is great. Appreciate you taking the time to note everything down.

**Comment by ziyadedher** [comment]
@SamWilsn [recommended trying w/ PyPy](https://twitter.com/_SamWilsn_/status/1578847198237757440?s=20&t=tb9k6WPbGkvDpXNz9sUdKA), it's a lot faster! ~4290ms per run w/ PyPy compared to ~15693ms w/ CPython. So `pyrevm` is "only" 37x faster than `pyevm` running in PyPy.

Below is a summary of results so far. This is on a i7-7700K CPU @ 4.20GHz.

| Runtime | Average time per `snailtracer` run (ms) | Relative time |
| ----------- | ---------------------------------- | -------------------- | 
| [`revm`](https://github.com/bluealloy/revm), rustc 1.64.0  | ~50 | x0.434 |
| [`pyrevm`](https://github.com/gakonst/pyrevm), rustc 1.64.0, cpython 3.10.7  | ~115 | x1.00 |
| [`py-evm`](https://github.com/ethereum/py-evm), pypy 7.3.9 (python 3.9.12) | ~4290 | x37.3 |
| [`py-evm`](https://github.com/ethereum/py-evm), cpython 3.10.7 | ~15693 | x136 |

**Comment by ziyadedher** [comment]
BTW I threw together https://github.com/ziyadedher/evm-bench, here's how pyrevm compares on a few different benchmarks against friends. I'll probably get geth in there at some point too.

|                         | py-evm.cpython | py-evm.pypy | pyrevm | revm   |
| ----------------------- | -------------- | ----------- | ------ | ------ |
| erc20.approval-transfer | 1.4258s        | 377.2ms     | 16.8ms | 10ms   |
| erc20.mint              | 1.4092s        | 347.8ms     | 14.4ms | 5.6ms  |
| erc20.transfer          | 1.9988s        | 420.8ms     | 22.6ms | 11.4ms |
| snailtracer             | 17.857s        | 5.17s       | 138ms  | 58ms   |
| ten-thousand-hashes     | 3.4344s        | 665.6ms     | 18.2ms | 7ms    |
|                         |                |             |        |        |
| **sum**                 | 26.1252s       | 6.9814s     | 210ms  | 92ms   |
| **relative**            | 124x           | 33.2x       | 1.00x  | 0.44x  |

**Pull request merged**
